### ISSUE TITLE
Not a code issue

### ISSUE THREAD

**Issue by lcarrasco79** [nsebhastian/react-express-cometchat-widget#3]
But the tutorial is from July 19, 2019 and I don't see the version selection while creating the CometChat app actually the new app screen seems to have much more options, was wondering if it uses v2 of the API and if that would work with the tutorial code.

**Comment by NathanSebhastian** [comment]
Yes, I think the tutorial is out of date. You can use the same principle, of listener and SDK, but need to adjust the function calls and so

**Comment by lcarrasco79** [comment]
The thing is that v1 seems to be supported only in Legacy regions, I do not know what the Legacy regions are, but for me running the CometChat app in US, didn't work since I assume US is tight to v2 API, what it worked for me is replacing the URL in the server app (Server.js) by

const url = 'https://api-us.cometchat.io/v2.0';

I came to this conclusion by testing v1 on postman which gave me the 401 error, then tried the v2 in postman and that work, so replaced by v2 in the app too.

Hope this helps.
